export const blockCategories = [
  {
    id: 'subject',
    category: '피사체 (Subject)',
    emoji: '🎯',
    description: '이미지의 주인공',
    attributes: [
      'a young woman',
      'an old man',
      'a child',
      'a warrior',
      'a wizard',
      'a robot',
      'a dragon',
      'a wolf',
      'a cat',
      'a fox',
      'a knight',
      'an astronaut',
    ],
  },
  {
    id: 'style',
    category: '스타일 (Style)',
    emoji: '🎨',
    description: '전체적인 예술 스타일',
    attributes: [
      'photorealistic',
      'oil painting',
      'watercolor',
      'digital art',
      'anime style',
      'pencil sketch',
      'concept art',
      'cinematic',
      'impressionist',
      'surrealist',
      'minimalist',
      'pixel art',
    ],
  },
  {
    id: 'lighting',
    category: '조명 (Lighting)',
    emoji: '💡',
    description: '빛의 방향과 분위기',
    attributes: [
      'golden hour',
      'soft studio lighting',
      'dramatic side lighting',
      'backlit',
      'neon lighting',
      'candlelight',
      'moonlight',
      'volumetric light',
      'overcast sky',
      'dappled sunlight',
      'rim lighting',
      'ambient occlusion',
    ],
  },
  {
    id: 'composition',
    category: '구도 (Composition)',
    emoji: '📐',
    description: '카메라 앵글과 프레임',
    attributes: [
      'close-up portrait',
      'wide shot',
      'aerial view',
      'low angle',
      'high angle',
      'rule of thirds',
      'symmetrical',
      'Dutch angle',
      'over the shoulder',
      'full body',
      'macro shot',
      'establishing shot',
    ],
  },
  {
    id: 'mood',
    category: '분위기 (Mood)',
    emoji: '🌙',
    description: '감정과 톤',
    attributes: [
      'mysterious',
      'epic',
      'serene',
      'melancholic',
      'joyful',
      'tense',
      'romantic',
      'eerie',
      'nostalgic',
      'whimsical',
      'dark and gritty',
      'ethereal',
    ],
  },
  {
    id: 'setting',
    category: '배경 (Setting)',
    emoji: '🏔️',
    description: '장소와 환경',
    attributes: [
      'enchanted forest',
      'futuristic city',
      'ancient ruins',
      'ocean cliff',
      'snowy mountain',
      'desert dunes',
      'underwater',
      'outer space',
      'cozy cafe',
      'dark dungeon',
      'cherry blossom park',
      'stormy sea',
    ],
  },
  {
    id: 'color',
    category: '색감 (Color Palette)',
    emoji: '🌈',
    description: '전체 색상 톤',
    attributes: [
      'warm tones',
      'cool tones',
      'monochrome',
      'pastel colors',
      'vibrant colors',
      'muted palette',
      'earth tones',
      'neon colors',
      'black and white',
      'golden tones',
      'purple and teal',
      'sunset gradient',
    ],
  },
  {
    id: 'quality',
    category: '품질 (Quality)',
    emoji: '⭐',
    description: '렌더링 품질 태그',
    attributes: [
      'ultra detailed',
      '8k resolution',
      'masterpiece',
      'award winning',
      'trending on artstation',
      'sharp focus',
      'high quality',
      'professional',
      'intricate details',
      'hyper realistic',
    ],
  },
]

export const parameterOptions = [
  { id: 'ar_1_1', label: '--ar 1:1', group: '비율' },
  { id: 'ar_16_9', label: '--ar 16:9', group: '비율' },
  { id: 'ar_9_16', label: '--ar 9:16', group: '비율' },
  { id: 'ar_4_3', label: '--ar 4:3', group: '비율' },
  { id: 'v6', label: '--v 6', group: '버전' },
  { id: 'v6_1', label: '--v 6.1', group: '버전' },
  { id: 'niji6', label: '--niji 6', group: '버전' },
  { id: 'style_raw', label: '--style raw', group: '스타일' },
  { id: 'q2', label: '--q 2', group: '품질' },
  { id: 's750', label: '--s 750', group: '스타일화' },
  { id: 's1000', label: '--s 1000', group: '스타일화' },
]
